<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <link name="base_footprint"/>
  <!--link name="thruster_1"/>
  <link name="thruster_2"/!-->

  <xacro:property name="p" value="3.141592653589793"/>
  <xacro:property name="auv_volume"  value="0.06157521601"/>
  <xacro:property name="auv_length"  value="1.0"/>
  <xacro:property name="auv_width"   value="0.14"/>
  <xacro:property name="auv_height"  value="0.14"/>
  <xacro:property name="auv_cob" value="0 0 0.07"/>

  <xacro:property name="R"          value="0.03" />
  <xacro:property name="W"          value="0.01" />


  
  <material name="yellow"> <color rgba="1.0 1.0 0.0 1.0"/></material>  
  <material name="black"><color rgba="0.1 0.1 0.1 1.0"/></material>

  <link name="body_link">
    <visual>
      <origin xyz="0 0 0" rpy="0  0 0"/>
      <geometry>
        <cylinder radius="${auv_width}" length="${auv_length}"/>
      </geometry>
      <material name="yellow"/>
    </visual>
   
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${auv_width}" length="${auv_length}"/>
      </geometry>
    </collision>
  
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="61.6"/>
      <inertia ixx="2.291666" ixy="0" ixz="0" iyy="4.125" iyz="0" izz="4.766652"/>
    </inertial>
  </link>
  
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child  link="body_link"/>
    <origin xyz="0 0 0.5" rpy="0 ${0.5*p} 0"/>
  </joint>

  <link name="thruster_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.0001866667" ixy="0" ixz="0" iyy="0.0001866667" iyz="0" izz="0.00036"/>
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${R}" length="${W}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${R}" length="${W}"/>
      </geometry>
    </collision>
  </link>

  <!--joint name="thrust_vector_yaw" type="revolute">
    <parent link="body_link"/>
    <child link="thruster_1"/>
    <origin rpy="0 0 0" xyz="0 0 0.51"/>
    <axis xyz="0 1 0"/>
    <limit effort="1.532" lower="${-0.08*p}" upper="${0.08*p}" velocity="7.19407"/>
  </joint>

  <joint name="thrust_vector_pitch" type="revolute">
    <parent link="thruster_1"/>
    <child link="thruster_2"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="1.532" lower="${-0.08*p}" upper="${0.08*p}" velocity="7.19407"/>
  </joint!-->

  <joint name="thrust_joint" type="continuous">
    <parent link="body_link"/>
    <child link="thruster_link"/>
    <origin rpy="0 0 0" xyz="0 0 ${auv_length/2}"/>
    <axis xyz="0 0 1"/>
  </joint>
  
  
  


</robot>